Repository joostlek/python-spotify, pull requests merged in 2024-10, with the labels that each got.

#293 Fix requesting playlist with different ids
  src/spotifyaio/spotify.py
  tests/test_playlist.py
Labels: bugfix

#294 Clean up the tests
  tests/__snapshots__/test_playback.ambr
  tests/__snapshots__/test_playlist.ambr
  tests/__snapshots__/test_spotify.ambr
  tests/__snapshots__/test_user.ambr
  tests/test_client.py
  tests/test_playback.py
  tests/test_playlist.py
  tests/test_spotify.py
  tests/test_user.py
Labels: maintenance

#299 Add support for episodes
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/episode.json
  tests/test_spotify.py
Labels: new-feature

#300 Add support for shows
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/show.json
  tests/test_spotify.py
Labels: new-feature

#301 Support playing episodes
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/playback_episode_1.json
  tests/test_spotify.py
Labels: new-feature

#302 Support adding to queue
  src/spotifyaio/spotify.py
  tests/test_spotify.py
Labels: new-feature

#303 Add overlapping properties to item
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
Labels: bugfix

#304 Add models to `__all__`
  src/spotifyaio/__init__.py
Labels: maintenance

#305 Add support for fetching followed artists
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/followed_artists.json
  tests/test_spotify.py
Labels: new-feature

#307 Add support for fetching saved albums
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/saved_albums.json
  tests/test_spotify.py
Labels: new-feature

#308 Add support for fetching saved tracks
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/saved_tracks.json
  tests/test_spotify.py
Labels: new-feature

#309 Add support for fetching saved shows
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/saved_shows.json
  tests/test_spotify.py
Labels: new-feature

#310 Add support for fetching recently played tracks
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/recently_played_tracks.json
  tests/test_spotify.py
Labels: new-feature

#311 Add support for fetching top artists and tracks
  .pre-commit-config.yaml
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/top_artists.json
  tests/fixtures/top_tracks.json
  tests/test_spotify.py
Labels: new-feature

#312 Add support for fetching a category
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/category.json
  tests/test_spotify.py
Labels: new-feature

#313 Add support for fetching new releases
  .pre-commit-config.yaml
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/new_releases.json
  tests/test_spotify.py
Labels: new-feature

#314 Add support for fetching an artist
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/artist.json
  tests/test_spotify.py
Labels: new-feature

#316 Add support for fetching episodes of a show
  .pre-commit-config.yaml
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/show_episodes.json
  tests/test_spotify.py
Labels: new-feature

#317 Add images to artist
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
Labels: bugfix

#319 Remove blocking call
  src/spotifyaio/spotify.py
Labels: bugfix

#320 Make email nullable
  src/spotifyaio/models.py
Labels: bugfix

#322 Add support for fetching categories
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/categories.json
  tests/test_spotify.py
Labels: new-feature

#323 Add tracks in playlist
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
Labels: new-feature

#324 Handle optional images
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/current_user_playlist_1.json
  tests/fixtures/current_user_playlist_2.json
  tests/test_spotify.py
Labels: bugfix

#325 Handle null album in saved albums
  src/spotifyaio/models.py
  tests/fixtures/saved_albums.json
Labels: bugfix

#326 Handle null context in played tracks
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/recently_played_tracks.json
Labels: bugfix

#327 Make lowercasing album preserialization a hook
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
Labels: bugfix

#328 Fix generic type in album tracks
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
Labels: bugfix

#329 Fix sending JSON
  src/spotifyaio/spotify.py
  tests/test_spotify.py
Labels: bugfix

#346 Fix audiobook playback
  .pre-commit-config.yaml
  src/spotifyaio/models.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/playback_audiobook_1.json
  tests/test_spotify.py
Labels: bugfix

#347 Migrate pre-commit config
  .pre-commit-config.yaml
Labels: maintenance

#348 Add list of things still left and reoder
  src/spotifyaio/spotify.py
Labels: maintenance

#349 Get list of albums
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  src/spotifyaio/util.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/albums.json
  tests/test_spotify.py
Labels: new-feature

#350 Get tracks of album
  .pre-commit-config.yaml
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/album_tracks.json
  tests/test_spotify.py
Labels: new-feature

#351 Save albums
  src/spotifyaio/spotify.py
  tests/test_spotify.py
Labels: new-feature

#352 Removing saved albums
  src/spotifyaio/spotify.py
  tests/test_spotify.py
Labels: new-feature

#353 Check saved album
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/album_saved.json
  tests/test_spotify.py
Labels: new-feature

#354 Add support for retrieving audio features
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/audio_features.json
  tests/test_spotify.py
Labels: new-feature

#355 Add py.typed file
  src/spotifyaio/py.typed
Labels: bugfix

#357 Add support for fetching multiple audiobooks
  src/spotifyaio/models.py
  src/spotifyaio/spotify.py
  tests/__snapshots__/test_spotify.ambr
  tests/fixtures/audiobooks.json
  tests/test_spotify.py
Labels: new-feature

#375 Add missing device type: Automobile
  src/spotifyaio/models.py
Labels: bugfix

#376 Add audio dongle as supported DeviceType
  src/spotifyaio/models.py
Labels: bugfix

#377 Rename Key enum values
  src/spotifyaio/models.py
Labels: bugfix

#378 Add CastVideo as supported DeviceType
  src/spotifyaio/models.py
Labels: bugfix
